name: complex-bin-packing-GA
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - contourpy=1.3.0
  - cycler=0.12.1
  - fonttools=4.54.1
  - freetype=2.12.1
  - kiwisolver=1.4.7
  - lcms2=2.16
  - lerc=4.0.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcxx=19.1.2
  - libdeflate=1.22
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=3.0.0
  - libopenblas=0.3.21
  - libpng=1.6.44
  - libsqlite=3.47.0
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - matplotlib-base=3.9.2
  - munkres=1.1.4
  - ncurses=6.5
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pillow=11.0.0
  - pip=23.3
  - pthread-stubs=0.4
  - pyparsing=3.2.0
  - python=3.12.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - qhull=2020.2
  - readline=8.2
  - scienceplots=2.1.1
  - setuptools=68.0.0
  - six=1.16.0
  - tk=8.6.13
  - tzdata=2023c
  - unicodedata2=15.1.0
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.4.2
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - bottleneck==1.3.6
      - dill==0.3.9
      - holidays==0.57
      - immutabledict==4.2.0
      - ortools==9.10.4067
      - pandas==2.2.3
      - protobuf==5.28.0
      - tqdm==4.66.5
